In [1]:
import torch

In [2]:
a = torch.rand(2, 3)
print(a)

tensor([[0.0880, 0.3048, 0.0417],
        [0.7777, 0.0019, 0.2381]])


In [3]:
print(torch.cos(a))
print(torch.sin(a))

tensor([[0.9961, 0.9539, 0.9991],
        [0.7125, 1.0000, 0.9718]])
tensor([[0.0878, 0.3001, 0.0417],
        [0.7017, 0.0019, 0.2359]])


In [11]:
# torch.manual_seed(1)
a = torch.rand(2, 3)
print(torch.normal(mean=a, std=0.1))

tensor([[0.7260, 0.5903, 0.6681],
        [0.7026, 0.5858, 0.7830]])


In [13]:
a = torch.rand(1, 1)
print(a)
print(torch.norm(a, p=2))
print(torch.norm(a, p=1))

tensor([[0.1251]])
tensor(0.1251)
tensor(0.1251)
