In [ ]:
import torch

# 创建张量
tensor1 = torch.tensor([1, 2, 3])  # 从列表创建张量
tensor2 = torch.zeros((2, 3))  # 创建全零张量
tensor3 = torch.ones((2, 3))  # 创建全一张量
tensor4 = torch.rand((2, 3))  # 创建随机张量

# 张量的基本属性
print(tensor1.shape)  # 查看张量的形状
print(tensor1.dtype)  # 查看张量的数据类型
print(tensor1.device)  # 查看张量所在的设备（CPU/GPU）

# 张量的基本操作
tensor5 = tensor1 + 1  # 张量加法
tensor6 = tensor1 * 2  # 张量乘法
tensor7 = tensor1 @ tensor1.T  # 矩阵乘法（点积）
tensor8 = tensor1.sum()  # 求和
tensor9 = tensor1.mean()  # 求均值

# 改变张量形状
tensor10 = tensor2.view(3, 2)  # 改变形状
tensor11 = tensor2.reshape(3, 2)  # 改变形状（类似view）

# 张量与NumPy的互操作
import numpy as np

array = np.array([1, 2, 3])
tensor12 = torch.from_numpy(array)  # NumPy数组转张量
array2 = tensor12.numpy()  # 张量转NumPy数组

# 张量在GPU上的操作
if torch.cuda.is_available():
    tensor13 = tensor1.to("cuda")  # 将张量移动到GPU
    print(tensor13.device)

In [16]:
import torch

# 创建张量
x = torch.tensor([[3, 2], [3, 1]])
x = torch.zeros((2, 3))  # 创建全零张量
x = torch.zeros(3)
x = torch.zeros_like(torch.tensor([[1, 2], [3, 4]]))  # 创建与给定张量相同形状的全零张量
x = torch.ones((2, 3))  # 创建全一张量
x = torch.rand((2, 3))  # 创建随机张量
x = torch.randn((2, 3))  # 创建标准正态分布随机张量
x = torch.randint(0, 10, (2, 3))  # 创建随机整数张量
x

tensor([[3, 0, 5],
        [7, 1, 8]])

In [ ]:
x.shape
x.dtype
x.device  # 查看张量所在的设备（CPU/GPU）

device(type='cpu')

In [29]:
x1 = torch.tensor([1.0, 2.0, 3.0])  # 从列表创建张量
x2 = torch.tensor([[4, 5, 6]])  # 从嵌套列表创建张量
x = x1 + 1  # 张量加法
x = x1 * 2  # 张量乘法
x = x2 @ x2.T  # 矩阵乘法（点积）
x = x1.sum()  # 求和
x = x1.mean()  # 求均值
x

tensor(2.)

In [34]:
x = x1.view(3, 1)  # 改变形状
x = x1.reshape(3, 1)  # 改变形状（类似view）
x

tensor([[1.],
        [2.],
        [3.]])

In [36]:
import numpy as np

x = torch.from_numpy(np.array([[1, 2], [3, 4]]))  # NumPy数组转张量
x = x.numpy()  # 张量转NumPy数组
x

array([[1, 2],
       [3, 4]])